export default function Footer() {
  return (
    <footer className="mt-auto border-t border-slate-200 bg-white/60 px-6 py-6 text-center text-xs text-slate-500">
      <p className="mx-auto max-w-2xl">
        <span className="font-medium text-slate-600">AI Disclaimer:</span>{' '}
        Responses are generated by AI and may not always be accurate. Please
        verify critical information with official government sources.
      </p>
      <p className="mt-2">&copy; {new Date().getFullYear()} OpenCivic</p>
    </footer>
  );
}
